export BASH_SILENCE_DEPRECATION_WARNING=1
export PS1='\u@\h:\[\e[01;32m\]\w\[\e[0m\]\$ '
export EDITOR='vim'
export CLICOLOR=1

if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

export PATH="${HOME}/.local/bin:${PATH}"

# libomp (Homebrew) for some C++ builds
if [[ -d "$(brew --prefix 2>/dev/null)/opt/libomp" ]]; then
  export CPLUS_INCLUDE_PATH="$(brew --prefix)/opt/libomp/include${CPLUS_INCLUDE_PATH:+:$CPLUS_INCLUDE_PATH}"
  export DYLD_LIBRARY_PATH="$(brew --prefix)/opt/libomp/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
fi

export NVM_DIR="${HOME}/.nvm"
# shellcheck disable=SC1091
[[ -s "${NVM_DIR}/nvm.sh" ]] && . "${NVM_DIR}/nvm.sh"
# shellcheck disable=SC1091
[[ -s "${NVM_DIR}/bash_completion" ]] && . "${NVM_DIR}/bash_completion"

# shellcheck disable=SC1091
[[ -s "${HOME}/.cargo/env" ]] && . "${HOME}/.cargo/env"

# Go (official pkg)
[[ -d /usr/local/go/bin ]] && export PATH="/usr/local/go/bin:${PATH}"

# Prefer repo bashrc for aliases when present
# shellcheck disable=SC1090
[[ -f "${HOME}/.bashrc" ]] && . "${HOME}/.bashrc"
